name: vehical_app
description: "Vehical app on flutter"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  supabase_flutter: ^2.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.2"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/


flutter_launcher_icons:
  image_path: "assets/IconApp.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/IconApp.png"